#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define EXIT_SUCESS 0
#define ASSERT_CONDITION_RESOLVES_TO_NON_BOOLEAN 100
#define MEMORY_ALLOCATION_FOR_TESTS_FAILED 101
#define TESTS_FAILED_ERROR_CODE 1

#endif // !ERROR_CODES_H
